### ISSUE TITLE
stray dataset import

### ISSUE THREAD

**Issue by xXValiXx** [StrayRobots/issues#1]
**Describe the bug**

I want to import the dataset with stray dataset import and i am getting a SyntaxError: invalid syntax while executing the command. 
`stray dataset import`
`File "/home/testuser/.stray/env/bin/straylib-dataset-import", line 5` 
    `from scripts.import import main`
               `^` 
`SyntaxError: invalid syntax`

**To Reproduce**
1. Install Stray with the installation script
2. execute: `source ~/.bashrc`
3. try to execute the command: `stray dataset import`

**Expected behavior**

Import data from the Stray Scanner app into the scene format

**Screenshots**

![grafik](https://user-images.githubusercontent.com/47116168/132844406-17ef1a26-2071-40aa-b2bc-0c1d56fdefae.png)

**Desktop (please complete the following information):**
 - OS: [Centos]
 - Version [7.9.2009]

**Additional context**
![grafik](https://user-images.githubusercontent.com/47116168/132847215-e9989701-c17d-4c61-9579-c29fb2cd969a.png)

Something went wrong while installing.

**Comment by hietalajulius** [comment]
Hello!

We just pushed a new linux build, hopefully that fixes the issue. Also as mentioned in https://github.com/StrayRobots/issues/issues/2, `curl --proto '=https' --tlsv1.2 -sSf https://stray-builds.ams3.digitaloceanspaces.com/cli/install.sh | bash` should work for the install.
